import type { ContentDefinition, ObjectType } from "./types";

export const CONTENT: Record<ObjectType, ContentDefinition> = {
  entrance: {
    id: "entrance",
    nameKey: "object.entrance",
    descriptionKey: "desc.entrance",
    category: "objects",
    cost: 0,
    behavior: "spawn",
    color: "#78bbb2",
  },
  treasure: {
    id: "treasure",
    nameKey: "object.treasure",
    descriptionKey: "desc.treasure",
    category: "objects",
    cost: 10,
    behavior: "goal",
    color: "#e6ba66",
  },
  key: {
    id: "key",
    nameKey: "object.key",
    descriptionKey: "desc.key",
    category: "objects",
    cost: 3,
    behavior: "key",
    color: "#e6ba66",
  },
  door: {
    id: "door",
    nameKey: "object.door",
    descriptionKey: "desc.door",
    category: "objects",
    cost: 2,
    behavior: "door",
    color: "#bfa071",
  },
  potion: {
    id: "potion",
    nameKey: "object.potion",
    descriptionKey: "desc.potion",
    category: "objects",
    cost: 5,
    behavior: "heal",
    damage: 35,
    color: "#85bb8c",
  },
  spikes: {
    id: "spikes",
    nameKey: "object.spikes",
    descriptionKey: "desc.spikes",
    category: "traps",
    cost: 6,
    behavior: "trap",
    damage: 18,
    cooldown: 4,
    color: "#b1b9ad",
  },
  fire: {
    id: "fire",
    nameKey: "object.fire",
    descriptionKey: "desc.fire",
    category: "traps",
    cost: 8,
    behavior: "trap",
    damage: 12,
    cooldown: 2,
    color: "#ec9563",
  },
  skeleton: {
    id: "skeleton",
    nameKey: "object.skeleton",
    descriptionKey: "desc.skeleton",
    category: "monsters",
    cost: 8,
    behavior: "enemy",
    hp: 36,
    damage: 8,
    range: 1,
    cooldown: 2,
    color: "#dfd7bc",
  },
  archer: {
    id: "archer",
    nameKey: "object.archer",
    descriptionKey: "desc.archer",
    category: "monsters",
    cost: 10,
    behavior: "enemy",
    hp: 24,
    damage: 7,
    range: 3,
    cooldown: 3,
    color: "#b7a2c9",
  },
  slime: {
    id: "slime",
    nameKey: "object.slime",
    descriptionKey: "desc.slime",
    category: "monsters",
    cost: 6,
    behavior: "enemy",
    hp: 24,
    damage: 5,
    range: 1,
    cooldown: 1,
    color: "#91b977",
  },
  guardian: {
    id: "guardian",
    nameKey: "object.guardian",
    descriptionKey: "desc.guardian",
    category: "monsters",
    cost: 16,
    behavior: "enemy",
    hp: 72,
    damage: 14,
    range: 1,
    cooldown: 3,
    color: "#a0a9aa",
  },
};
